### ISSUE TITLE
Cannot delete "Section" element after creating it

### ISSUE THREAD

**Issue by TheTrainTrain** [Open-MBEE/ve#212]
After adding a Section to a View, it is impossible to delete it. It loads the deletion forever without ever completing the deletion.

**Comment by dlamoris** [comment]
can you give the versions of ve/mms being used? and any console errors?
if possible, consider joining the dev tagups https://www.openmbee.org/calendar.html so it's easier to debug

**Comment by TheTrainTrain** [comment]
> can you give the versions of ve/mms being used? and any console errors? if possible, consider joining the dev tagups https://www.openmbee.org/calendar.html so it's easier to debug

Thanks for the reply! I will start attending the tagups. How do I check the version of VE I am using?

There is no delete button available for the subsection, so I tried to delete the view that hosts the subsection and got greeted with this error in the console:
TypeError: $scope.treeApi.get_parent_branch is not a function
    at $scope.ok (tree.controller.js:833:51)
    at fn (eval at compile (params.js:13:2), <anonymous>:4:126)
    at callback (params.js:13:2)
    at Scope.$eval (params.js:13:2)
    at Scope.$apply (params.js:13:2)
    at HTMLButtonElement.<anonymous> (params.js:13:2)
    at HTMLButtonElement.dispatch (params.js:13:2)
    at elemData.handle (params.js:13:2) undefined

**Comment by TheTrainTrain** [comment]
VE Version: 4.0.0-RC1
MMS Version: 4.0.8b-LDAP-USER-SEARCH

**Comment by dlamoris** [comment]
you'll want to update both to the latest version i think (ve 4.0.2, mms 4.0.18)
